import type {
  Company,
  DailyBrief,
  IntelligenceUpdate,
  ResearchSource,
  StackLayer,
} from "../../shared/contracts.js";
import { SOURCE_CATALOG_ROWS } from "../ingestion/source-registry.js";

export const seedLayers: StackLayer[] = [
  {
    id: "model-labs",
    name: "Model labs",
    description: "Organizations training and operating frontier and specialized models.",
    companyTickers: [],
    dependsOn: ["cloud", "serving"],
  },
  {
    id: "cloud",
    name: "Cloud providers",
    description: "Hyperscale capacity, data-center operations, and managed AI platforms.",
    companyTickers: [],
    dependsOn: ["accelerators", "networking", "power-cooling"],
  },
  {
    id: "accelerators",
    name: "Accelerators",
    description: "GPUs and custom silicon that perform model training and inference.",
    companyTickers: ["NVDA", "AMD", "AVGO", "MRVL"],
    dependsOn: ["memory", "manufacturing"],
  },
  {
    id: "memory",
    name: "Memory",
    description: "High-bandwidth memory and storage feeding AI compute.",
    companyTickers: ["MU"],
    dependsOn: ["manufacturing", "materials-builders"],
  },
  {
    id: "networking",
    name: "Networking",
    description: "Switching, interconnects, and fabrics joining accelerators at scale.",
    companyTickers: ["NVDA", "AVGO", "MRVL", "ANET"],
    dependsOn: ["optics", "manufacturing"],
  },
  {
    id: "optics",
    name: "Optics",
    description: "Optical components, transceivers, and fiber carrying data between systems.",
    companyTickers: ["COHR", "LITE", "GLW"],
    dependsOn: ["manufacturing", "materials-builders"],
  },
  {
    id: "power-cooling",
    name: "Power and cooling",
    description: "Electrical distribution, generation, thermal management, and data-center infrastructure.",
    companyTickers: ["VRT", "ETN", "GEV"],
    dependsOn: ["materials-builders"],
  },
  {
    id: "serving",
    name: "Serving software",
    description: "Inference runtimes, schedulers, kernels, and orchestration software.",
    companyTickers: ["NVDA", "AMD"],
    dependsOn: ["accelerators", "cloud"],
  },
  {
    id: "manufacturing",
    name: "Manufacturing",
    description: "Leading-edge wafer fabrication, advanced packaging, and assembly.",
    companyTickers: ["TSM"],
    dependsOn: ["materials-builders"],
  },
  {
    id: "materials-builders",
    name: "Materials, suppliers, and builders",
    description: "Equipment, substrates, commodities, construction, and upstream capacity.",
    companyTickers: ["GLW", "GEV"],
    dependsOn: [],
  },
];

const updatedAt = "2026-06-27T00:00:00.000Z";

export const seedCompanies: Company[] = [
  {
    ticker: "NVDA",
    name: "NVIDIA",
    layerIds: ["accelerators", "networking", "serving"],
    description: "The dominant full-stack supplier of accelerated AI computing.",
    thesis: "NVIDIA can preserve premium economics by improving the whole AI factory, not only the GPU.",
    whyItMatters: "Its compute, NVLink, networking, CUDA, and inference software define the reference architecture for scaled AI.",
    provesRight: ["Data-center growth remains durable", "Rubin deploys on schedule", "Networking and software attach rates rise"],
    breaksThesis: ["Custom accelerators take materially more workloads", "Platform transitions slip", "CUDA lock-in weakens"],
    watchMetrics: ["Data-center revenue", "Gross margin", "Cloud capex", "Rubin availability"],
    confidence: "high",
    updatedAt,
  },
  {
    ticker: "AMD",
    name: "Advanced Micro Devices",
    layerIds: ["accelerators", "serving"],
    description: "A scaled alternative accelerator platform with CPUs, GPUs, and open software.",
    thesis: "AMD can become the credible second source for large AI deployments as ROCm and rack-scale systems mature.",
    whyItMatters: "A viable second platform changes buyer leverage and expands accelerator supply.",
    provesRight: ["MI-series deployments broaden", "ROCm performance gaps close", "Major clouds offer production capacity"],
    breaksThesis: ["Software friction persists", "Roadmaps slip", "Customers limit AMD to experiments"],
    watchMetrics: ["Data-center GPU revenue", "ROCm releases", "Cloud instance availability", "Customer concentration"],
    confidence: "medium",
    updatedAt,
  },
  {
    ticker: "AVGO",
    name: "Broadcom",
    layerIds: ["accelerators", "networking"],
    description: "A leader in custom AI silicon and Ethernet switching.",
    thesis: "Custom XPUs and Ethernet fabrics will capture a growing share of hyperscaler AI spending.",
    whyItMatters: "Broadcom is positioned at both custom compute and the network joining it.",
    provesRight: ["More hyperscalers deploy XPUs", "AI semiconductor revenue compounds", "Ethernet scales to larger clusters"],
    breaksThesis: ["Custom silicon adoption slows", "Margins compress", "Proprietary fabrics retain most deployments"],
    watchMetrics: ["AI semiconductor revenue", "XPU customer count", "Tomahawk and Jericho ramps", "Semiconductor margins"],
    confidence: "high",
    updatedAt,
  },
  {
    ticker: "MRVL",
    name: "Marvell Technology",
    layerIds: ["accelerators", "networking"],
    description: "Custom silicon, interconnect, DSP, and data infrastructure supplier.",
    thesis: "Marvell can convert a broad custom-silicon pipeline into durable AI revenue while optics connectivity scales.",
    whyItMatters: "It connects custom compute design wins with the electro-optical links needed to deploy them.",
    provesRight: ["Custom programs enter volume production", "Electro-optics revenue accelerates", "Design wins diversify"],
    breaksThesis: ["Programs are delayed or concentrated", "Broadcom wins key sockets", "Optical attach grows slower than expected"],
    watchMetrics: ["Data-center revenue", "Custom program ramps", "Electro-optics growth", "Customer concentration"],
    confidence: "medium",
    updatedAt,
  },
  {
    ticker: "ANET",
    name: "Arista Networks",
    layerIds: ["networking"],
    description: "High-speed Ethernet switching and operating software for cloud networks.",
    thesis: "Ethernet will remain a central scale-out fabric, allowing Arista to compound with AI cluster bandwidth.",
    whyItMatters: "Every larger accelerator cluster increases east-west traffic and network complexity.",
    provesRight: ["800G and 1.6T adoption accelerates", "AI back-end deployments diversify", "Cloud customers maintain capex"],
    breaksThesis: ["Proprietary interconnect dominates", "Hyperscalers insource switching", "Customer concentration worsens"],
    watchMetrics: ["Cloud titan revenue", "800G shipments", "Back-end network wins", "Operating margin"],
    confidence: "high",
    updatedAt,
  },
  {
    ticker: "COHR",
    name: "Coherent",
    layerIds: ["optics"],
    description: "Optical transceivers, lasers, and compound-semiconductor components.",
    thesis: "AI cluster bandwidth growth will tighten advanced optics supply and improve Coherent's mix and utilization.",
    whyItMatters: "Compute cannot scale economically if data cannot move between racks and campuses.",
    provesRight: ["800G and 1.6T demand outpaces capacity", "Datacom margins expand", "Indium phosphide capacity stays constrained"],
    breaksThesis: ["Optics commoditizes", "Capacity overshoots", "Copper or co-packaged optics reduces addressable content"],
    watchMetrics: ["Datacom revenue", "1.6T qualification", "Laser utilization", "Gross margin"],
    confidence: "medium",
    updatedAt,
  },
  {
    ticker: "LITE",
    name: "Lumentum",
    layerIds: ["optics"],
    description: "Supplier of optical and photonic components for cloud data links.",
    thesis: "Higher-speed cloud networking will pull Lumentum's advanced laser capacity into a structurally stronger cycle.",
    whyItMatters: "Laser supply is a critical upstream constraint for high-speed transceivers.",
    provesRight: ["Cloud and networking revenue accelerates", "Laser capacity is pre-committed", "Margins recover with mix"],
    breaksThesis: ["Customer qualifications slip", "New supply causes pricing pressure", "Demand stays concentrated"],
    watchMetrics: ["Cloud and networking revenue", "Order coverage", "Gross margin", "Customer concentration"],
    confidence: "medium",
    updatedAt,
  },
  {
    ticker: "GLW",
    name: "Corning",
    layerIds: ["optics", "materials-builders"],
    description: "Fiber, cable, and connectivity systems for hyperscale data centers.",
    thesis: "AI data-center density and campus scale will increase fiber content faster than general data-center growth.",
    whyItMatters: "More accelerators and faster links require substantially more physical fiber connectivity.",
    provesRight: ["Enterprise optical sales outgrow the market", "Hyperscaler agreements expand", "Fiber content per campus rises"],
    breaksThesis: ["Build schedules slow", "Pricing weakens", "Connectivity intensity grows below expectations"],
    watchMetrics: ["Optical communications sales", "Hyperscaler commitments", "Capacity additions", "Segment margin"],
    confidence: "medium",
    updatedAt,
  },
  {
    ticker: "MU",
    name: "Micron Technology",
    layerIds: ["memory"],
    description: "A major supplier of HBM and advanced DRAM for AI accelerators.",
    thesis: "HBM complexity and qualification create a durable mix uplift and keep leading memory supply disciplined.",
    whyItMatters: "Accelerators are constrained by memory bandwidth as much as raw compute.",
    provesRight: ["HBM remains sold ahead", "HBM share improves", "DRAM pricing stays disciplined"],
    breaksThesis: ["Competitors widen the technology gap", "Supply additions exceed demand", "Accelerator architectures reduce HBM content"],
    watchMetrics: ["HBM revenue and share", "DRAM bit growth", "Gross margin", "HBM4 qualification"],
    confidence: "high",
    updatedAt,
  },
  {
    ticker: "VRT",
    name: "Vertiv",
    layerIds: ["power-cooling"],
    description: "Critical power and thermal systems for high-density data centers.",
    thesis: "AI rack density creates a multi-year retrofit and greenfield cycle for power delivery and liquid cooling.",
    whyItMatters: "Available megawatts and heat removal increasingly gate accelerator deployment.",
    provesRight: ["Orders and backlog remain elevated", "Liquid-cooling attach rises", "Capacity expands without execution loss"],
    breaksThesis: ["AI projects are deferred", "Backlog converts slowly", "Competition compresses margins"],
    watchMetrics: ["Organic orders", "Book-to-bill", "Backlog", "Liquid cooling revenue"],
    confidence: "high",
    updatedAt,
  },
  {
    ticker: "ETN",
    name: "Eaton",
    layerIds: ["power-cooling"],
    description: "Electrical distribution and power-management equipment supplier.",
    thesis: "Grid constraints and data-center load growth will sustain demand for electrical equipment and power quality.",
    whyItMatters: "Transformers, switchgear, and power distribution sit on the critical path before servers can energize.",
    provesRight: ["Electrical backlog stays elevated", "Data-center orders broaden", "Pricing offsets capacity investment"],
    breaksThesis: ["Utility interconnections stall projects", "Capacity catches demand", "Industrial spending rolls over"],
    watchMetrics: ["Electrical Americas orders", "Backlog", "Data-center mix", "Segment margin"],
    confidence: "high",
    updatedAt,
  },
  {
    ticker: "GEV",
    name: "GE Vernova",
    layerIds: ["power-cooling", "materials-builders"],
    description: "Generation and grid equipment provider exposed to incremental data-center electricity demand.",
    thesis: "AI load growth will accelerate investment in generation, grid equipment, and firm power capacity.",
    whyItMatters: "Data centers require reliable generation and grid connections long before compute arrives.",
    provesRight: ["Gas and grid backlogs expand", "Data-center-linked orders emerge", "Service revenue compounds"],
    breaksThesis: ["Load forecasts are revised down", "Permitting blocks projects", "Alternative supply displaces expected equipment demand"],
    watchMetrics: ["Gas power backlog", "Grid orders", "Turbine slots", "Service margins"],
    confidence: "medium",
    updatedAt,
  },
  {
    ticker: "TSM",
    name: "Taiwan Semiconductor Manufacturing",
    layerIds: ["manufacturing"],
    description: "The leading foundry for advanced AI silicon and advanced packaging.",
    thesis: "Leading-edge logic and packaging scarcity give TSMC durable pricing power across competing accelerator architectures.",
    whyItMatters: "NVIDIA, AMD, and custom accelerators converge on the same limited manufacturing base.",
    provesRight: ["Leading-node utilization stays high", "CoWoS capacity is absorbed", "Overseas fabs ramp economically"],
    breaksThesis: ["AI demand corrects", "Packaging capacity overshoots", "Geopolitical or execution risk disrupts supply"],
    watchMetrics: ["HPC revenue", "3nm and 2nm mix", "CoWoS capacity", "Capital expenditure"],
    confidence: "high",
    updatedAt,
  },
];

export const seedSources: ResearchSource[] =
  SOURCE_CATALOG_ROWS.map((source) => ({ ...source }));

export const seedUpdates: IntelligenceUpdate[] = [
  {
    id: "nvda-fy26-q4",
    title: "NVIDIA data-center revenue reaches $62.3 billion",
    publisher: "NVIDIA Investor Relations",
    sourceUrl: "https://investor.nvidia.com/news/press-release-details/2026/NVIDIA-Announces-Financial-Results-for-Fourth-Quarter-and-Fiscal-2026/",
    publishedAt: "2026-02-25T21:00:00.000Z",
    ingestedAt: "2026-02-25T21:10:00.000Z",
    layerIds: ["accelerators", "networking"],
    companyTickers: ["NVDA", "TSM", "MU"],
    materiality: "high",
    materialityReason: "Example demand evidence strengthens the seeded NVIDIA platform thesis.",
    novelty: "new",
    sentiment: "bullish",
    whatHappened: "NVIDIA reported record quarterly data-center revenue while guiding to another sequential increase.",
    whyItMatters: "The result confirms that demand for accelerated systems remains strong enough to pull manufacturing and HBM capacity with it.",
    beneficiaries: ["NVDA", "TSM", "MU"],
    threatened: ["Alternative accelerator platforms that are not scaling at the same rate"],
    watchNext: ["Rubin production availability", "Gross margin through the platform transition", "Cloud deployment timing"],
    claims: [{ id: "claim-nvda-dc", quote: "Record quarterly Data Center revenue of $62.3 billion, up 22% from Q3 and up 75% from a year ago", sourceId: "nvidia-ir", locator: "Q4 FY2026 results, highlights" }],
    thesisImpacts: [{ id: "impact-nvda-dc", companyTicker: "NVDA", direction: "bullish", summary: "Record growth supports the view that NVIDIA's platform demand remains structurally strong.", confidence: "high", horizon: "6–12 months", thesisDelta: "Strengthens confidence in durable platform demand.", decision: "proposed" }],
    model: null,
  },
  {
    id: "avgo-fy25-q4",
    title: "Broadcom expects AI semiconductor revenue to double",
    publisher: "Broadcom Investor Relations",
    sourceUrl: "https://investors.broadcom.com/news-releases/news-release-details/broadcom-inc-announces-fourth-quarter-and-fiscal-year-2025",
    publishedAt: "2025-12-11T21:00:00.000Z",
    ingestedAt: "2025-12-11T21:12:00.000Z",
    layerIds: ["accelerators", "networking"],
    companyTickers: ["AVGO", "MRVL", "ANET"],
    materiality: "high",
    materialityReason: "Example custom-silicon evidence strengthens the seeded Broadcom thesis.",
    novelty: "new",
    sentiment: "bullish",
    whatHappened: "Broadcom said custom accelerators and Ethernet switches were driving a sharp increase in AI semiconductor revenue.",
    whyItMatters: "This is direct evidence that hyperscaler custom compute and Ethernet are scaling as a parallel architecture to merchant GPUs.",
    beneficiaries: ["AVGO", "Ethernet ecosystem"],
    threatened: ["Competing custom silicon suppliers", "Proprietary-only networking assumptions"],
    watchNext: ["XPU customer concentration", "Ethernet switch mix", "Sustainability beyond the initial program ramps"],
    claims: [{ id: "claim-avgo-ai", quote: "We expect AI semiconductor revenue to double year-over-year to $8.2 billion", sourceId: "broadcom-ir", locator: "Q4 FY2025 results, CEO commentary" }],
    thesisImpacts: [{ id: "impact-avgo-ai", companyTicker: "AVGO", direction: "bullish", summary: "The outlook validates both legs of the custom XPU and Ethernet thesis.", confidence: "high", horizon: "3–12 months", thesisDelta: "Strengthens confidence in custom XPU and Ethernet adoption.", decision: "proposed" }],
    model: null,
  },
  {
    id: "vrt-fy25-q4",
    title: "Vertiv backlog doubles as AI power demand accelerates",
    publisher: "Vertiv Investor Relations",
    sourceUrl: "https://investors.vertiv.com/news/news-details/2026/Vertiv-Reports-Strong-Fourth-Quarter-with-Organic-Orders-Growth-of-252-and-Diluted-EPS-Growth-of-200-Adjusted-Diluted-EPS-37/",
    publishedAt: "2026-02-11T12:00:00.000Z",
    ingestedAt: "2026-02-11T12:08:00.000Z",
    layerIds: ["power-cooling"],
    companyTickers: ["VRT", "ETN", "GEV"],
    materiality: "high",
    materialityReason: "Example backlog evidence extends the expected power-infrastructure cycle.",
    novelty: "new",
    sentiment: "bullish",
    whatHappened: "Vertiv reported backlog of $15 billion, more than double the same period a year earlier.",
    whyItMatters: "Physical power and cooling infrastructure is being ordered far ahead of deployment, showing that megawatts are a binding AI constraint.",
    beneficiaries: ["VRT", "ETN", "GEV"],
    threatened: ["Projects dependent on short lead-time power equipment"],
    watchNext: ["Backlog conversion", "Cancellation rates", "Liquid-cooling production capacity"],
    claims: [{ id: "claim-vrt-backlog", quote: "backlog increased to $15.0 billion, up 109% compared to the same period last year", sourceId: "vertiv-ir", locator: "Q4 2025 results, financial highlights" }],
    thesisImpacts: [{ id: "impact-vrt-backlog", companyTicker: "VRT", direction: "bullish", summary: "Order coverage strongly supports a multi-year power and thermal infrastructure cycle.", confidence: "high", horizon: "12–24 months", thesisDelta: "Extends confidence in the duration of the power and cooling cycle.", decision: "proposed" }],
    model: null,
  },
  {
    id: "mu-hbm4-ramp",
    title: "Micron begins high-volume HBM4 production",
    publisher: "Micron Investor Relations",
    sourceUrl: "https://investors.micron.com/news-releases/news-release-details/micron-high-volume-production-hbm4-designed-nvidia-vera-rubin",
    publishedAt: "2026-03-16T21:00:00.000Z",
    ingestedAt: "2026-03-16T21:14:00.000Z",
    layerIds: ["memory"],
    companyTickers: ["MU", "NVDA", "AMD"],
    materiality: "medium",
    materialityReason: "Example production evidence confirms the HBM mix-upgrade thesis.",
    novelty: "confirmation",
    sentiment: "bullish",
    whatHappened: "Micron began high-volume production of 36GB HBM4 designed for NVIDIA's Vera Rubin platform.",
    whyItMatters: "A qualified HBM4 ramp reduces one system-level deployment risk and supports Micron's position in the highest-value part of memory.",
    beneficiaries: ["MU"],
    threatened: ["Accelerator schedules if qualification or supply slips"],
    watchNext: ["HBM4 customer qualification", "Yield progression", "Calendar 2027 supply commitments"],
    claims: [{ id: "claim-mu-hbm", quote: "HBM4 36GB 12H in high-volume production, designed for NVIDIA Vera Rubin", sourceId: "micron-ir", locator: "March 16, 2026 release, news highlights" }],
    thesisImpacts: [{ id: "impact-mu-hbm", companyTicker: "MU", direction: "bullish", summary: "High-volume HBM4 production reinforces the durable mix-upgrade thesis.", confidence: "high", horizon: "3–12 months", thesisDelta: "Raises confidence in HBM mix and production timing.", decision: "proposed" }],
    model: null,
  },
  {
    id: "nvda-dynamo-1",
    title: "NVIDIA ships Dynamo 1.0 for production inference",
    publisher: "NVIDIA Investor Relations",
    sourceUrl: "https://investor.nvidia.com/news/press-release-details/2026/NVIDIA-Enters-Production-With-Dynamo-the-Broadly-Adopted-Inference-Operating-System-for-AI-Factories/default.aspx",
    publishedAt: "2026-03-16T16:00:00.000Z",
    ingestedAt: "2026-03-16T16:09:00.000Z",
    layerIds: ["serving", "accelerators"],
    companyTickers: ["NVDA", "AMD"],
    materiality: "medium",
    materialityReason: "Example software release evidence strengthens full-stack differentiation.",
    novelty: "new",
    sentiment: "bullish",
    whatHappened: "NVIDIA moved its open-source Dynamo inference orchestration software into production release.",
    whyItMatters: "Serving efficiency can increase useful token output per installed GPU and deepen platform integration beyond hardware.",
    beneficiaries: ["NVDA", "Inference providers"],
    threatened: ["Standalone serving stacks without equivalent hardware integration"],
    watchNext: ["Independent benchmark results", "Production adoption", "Integration with open inference frameworks"],
    claims: [{ id: "claim-nvda-dynamo", quote: "Dynamo boosts inference performance of NVIDIA Blackwell GPUs by up to 7x", sourceId: "nvidia-ir", locator: "Dynamo 1.0 release, news summary" }],
    thesisImpacts: [{ id: "impact-nvda-dynamo", companyTicker: "NVDA", direction: "bullish", summary: "Production serving software strengthens NVIDIA's full-stack differentiation.", confidence: "medium", horizon: "3–12 months", thesisDelta: "Strengthens the software component of the full-stack thesis.", decision: "proposed" }],
    model: null,
  },
  {
    id: "avgo-jericho4",
    title: "Broadcom ships Jericho4 for distributed AI clusters",
    publisher: "Broadcom Investor Relations",
    sourceUrl: "https://investors.broadcom.com/news-releases/news-release-details/broadcom-ships-jericho4-enabling-distributed-ai-computing-across",
    publishedAt: "2025-08-04T13:00:00.000Z",
    ingestedAt: "2025-08-04T13:11:00.000Z",
    layerIds: ["networking"],
    companyTickers: ["AVGO", "ANET", "MRVL"],
    materiality: "medium",
    materialityReason: "Example deployment evidence broadens the Ethernet opportunity.",
    novelty: "new",
    sentiment: "bullish",
    whatHappened: "Broadcom introduced a routing chip designed to join AI compute across multiple data-center facilities.",
    whyItMatters: "Cluster scaling is moving from a single rack and building toward campus-scale fabrics, expanding the networking content per accelerator.",
    beneficiaries: ["AVGO", "Ethernet and optics suppliers"],
    threatened: ["Architectures unable to scale efficiently beyond one facility"],
    watchNext: ["Customer deployments", "Power per transported bit", "Optical port requirements"],
    claims: [{ id: "claim-avgo-jericho", quote: "Scales 1M+ XPU Clusters Beyond Single Facility Limits", sourceId: "broadcom-ir", locator: "Jericho4 release, subtitle" }],
    thesisImpacts: [{ id: "impact-anet-jericho", companyTicker: "ANET", direction: "bullish", summary: "Campus-scale AI validates a larger high-speed Ethernet switching opportunity.", confidence: "medium", horizon: "12–24 months", thesisDelta: "Broadens the expected addressable Ethernet deployment scope.", decision: "proposed" }],
    model: null,
  },
  {
    id: "tsm-packaging-signal",
    title: "TSMC says AI demand remains extremely robust",
    publisher: "TSMC Investor Relations",
    sourceUrl: "https://investor.tsmc.com/english/encrypt/files/encrypt_file/reports/2026-04/3cef85204275f94fd111485cfdf4adb3c0263c45/TSMC%201Q26%20Transcript.pdf",
    publishedAt: "2026-04-16T06:00:00.000Z",
    ingestedAt: "2026-04-16T06:15:00.000Z",
    layerIds: ["manufacturing", "accelerators", "memory"],
    companyTickers: ["TSM", "NVDA", "AMD", "AVGO", "MU"],
    materiality: "high",
    materialityReason: "Example packaging evidence reinforces manufacturing scarcity.",
    novelty: "confirmation",
    sentiment: "neutral",
    whatHappened: "TSMC described AI-related demand as extremely robust and outlined a multiyear capacity response.",
    whyItMatters: "Competing accelerator designs still converge on the same leading-edge manufacturing base, giving foundry demand a broader footing than any one chip vendor.",
    beneficiaries: ["TSM"],
    threatened: ["Accelerator ramps that assume unconstrained advanced packaging"],
    watchNext: ["CoWoS capacity additions", "Packaging lead times", "Customer prepayments"],
    claims: [{ id: "claim-tsm-packaging", quote: "AI-related demand continues to be extremely robust.", sourceId: "tsmc-ir", locator: "Q1 2026 earnings call transcript" }],
    thesisImpacts: [{ id: "impact-tsm-packaging", companyTicker: "TSM", direction: "bullish", summary: "Shared dependence on advanced packaging reinforces TSMC's strategic position.", confidence: "medium", horizon: "12–24 months", thesisDelta: "Strengthens confidence in advanced-packaging scarcity and pricing power.", decision: "proposed" }],
    model: null,
  },
];

export const seedBrief: DailyBrief = {
  id: "brief-2026-06-27",
  date: "2026-06-27",
  title: "Power delivery is becoming the schedule",
  summary: "The most important infrastructure signal is not another accelerator benchmark. Vertiv's order coverage shows that physical deployment capacity is being reserved far ahead of server delivery.",
  signal: "Vertiv's doubled backlog makes power and cooling a measurable deployment constraint, strengthening the VRT thesis while raising the importance of adjacent electrical and generation suppliers.",
  secondarySignals: [
    "Broadcom's custom-XPU and Ethernet outlook supports a parallel AI architecture.",
    "HBM4 qualification remains a critical dependency for the next accelerator cycle.",
    "Inference software is becoming a larger source of full-stack differentiation.",
  ],
  updateIds: ["vrt-fy25-q4", "avgo-fy25-q4", "mu-hbm4-ramp", "nvda-dynamo-1"],
  citationClaimIds: ["claim-vrt-backlog", "claim-avgo-ai", "claim-mu-hbm", "claim-nvda-dynamo"],
  generatedAt: "2026-06-27T06:00:00.000Z",
  model: null,
};
